services:
  - type: web
    name: django-chat-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p $PORT django_chat.asgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: django-chat-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: django-chat-redis
          property: connectionString

  - type: redis
    name: django-chat-redis
    plan: free

databases:
  - name: django-chat-db
    databaseName: chatdb
    user: chatuser
    plan: free 