# Generated by Django 4.2.16 on 2025-07-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
